# Uncomment the following when html tests are ready and replace above testing script
image: comp1531/basic:latest

stages:
 - checks

before_script:
 - npm install

tests:
 stage: checks
 only:
   - master
   - merge_requests
 script:
   - SERVER_LOG=$(mktemp)
   - npm run start >& $SERVER_LOG &
   - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || exit 1
   - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
   - kill -SIGINT %1
   - sleep 2
   - cat $SERVER_LOG

tsc:
  stage: checks
  script:
    - npm run tsc
  only:
    - master
    - merge_request

lint:
  stage: checks
  script:
    - npm run lint
  only:
    - master
    - merge_request
